### ISSUE TITLE
Precondition doesn't type check

### ISSUE THREAD

**Issue by nunoplopes** [nunoplopes/alive#29]
We should either reconsider adding +1 bit for positive numbers, have a way to downcast it or different syntax or...?
(test case from John Regehr)
```
Precondition: (computeKnownZeroBits(%in) == 4294443007)
   %1 = icmp eq i32 %in, 0
   %out = select i1 %1, 1, 2
=>
   %3 = lshr i32 %in, 20
   %out = add %3, 1

Precondition does not type check
```

**Comment by davemenendez** [comment]
I forget which problem that solved, but I agree it leads to surprises (e.g., "1" implies at least two bits). Do we still need to do that?

Assuming a way to indicate "signed positive int" is necessary, maybe something like "+1"?

**Comment by davemenendez** [comment]
The way we calculate minimum bit-widths for integer literals seems to be broken for negatives, as well.

```
>>> c = ConstantVal(-3, IntType())
>>> c.getTypeConstraints()
And(And(t_-3_0 == 0,
        Or(size_-3_0 == 8,
           size_-3_0 == 4,
           And(size_-3_0 > 0, size_-3_0 <= 64))),
    size_-3_0 >= 2)
```

Unfortunately, you can't represent -3 in two bits. I think't Python's `bit_length()` assumes an extra sign bit.

**Comment by davemenendez** [comment]
Here's an optimization which breaks if we don't assume sign bits for literals:

```
Name: AddSub:1156
%a = add %b, %b
  =>
%a = shl %b, 1
```

This is invalid in the 1-bit case, so we would need to add `Pre: width(%b) > 1` if positive literals did not add a sign bit.
