### ISSUE TITLE
Incorrect(?) undef semantics

### ISSUE THREAD

**Issue by davemenendez** [nunoplopes/alive#31]
Alive accepts this transformation:

```
%x = undef
%y = xor %x, %x
=>
%y = 0
```

However, the [language ref](http://llvm.org/docs/LangRef.html#undefined-values) seems to require `%y = undef`.

**Comment by nunoplopes** [comment]
This is fine. Removing undef is always ok.

**Comment by davemenendez** [comment]
I gave the example backward. The problem is that Alive rejects this:

```
%x = undef
%y = xor i8 %x, %x
=>
%y = undef
```

which the LLVM semantics seem to require.

```
----------------------------------------
Optimization: 1
Precondition: true
  %x = undef
  %y = xor i8 %x, %x
=>
  %y = undef


ERROR: Mismatch in values of i8 %y

Example:
%x i8 = 0x00 (0)
Source value: 0x00 (0)
Target value: 0xFF (255, -1)
```

**Comment by nunoplopes** [comment]
That's a bug, yes.

**Comment by nunoplopes** [comment]
This is fixed in newsema branch.
