### ISSUE TITLE
Python parse error on every example

### ISSUE THREAD

**Issue by arsenm** [nunoplopes/alive#33]
I'm unable to run this out of the box. If I try to run any of the samples, I get:
./alive.py tests/instcombine/addsub.opt        
Traceback (most recent call last):
  File "./alive.py", line 19, in <module>
    from parser import parse_llvm, parse_opt_file
  File "/Users/matt/src/alive/parser.py", line 304, in <module>
    pred_args <<= (cnst_expr + ZeroOrMore(comma + cnst_expr)) | Empty()
TypeError: Empty() takes exactly 1 argument (0 given)

If I remove the | Empty(), I'm able to run it.

**Comment by nunoplopes** [comment]
I'm sorry but I can't reproduce your problem.  Alive has been tested only with Python 2.7; does that match your configuration?
Also, can you confirm you don't have an old pyparsing library installed?

**Comment by arsenm** [comment]
I'm using Python 2.7.11 on OS X from macports. It seems to be using a copy of pyparsing checked into the repo

**Comment by davemenendez** [comment]
This is probably a conflict between z3 and pyparsing. Try moving the import of pyparsing after the import of language, so that the import block reads:

```python
import re
from language import *
from precondition import *
from pyparsing.pyparsing import *
```

Longer-term solutions include adding explicit export lists and qualified library imports.

**Comment by arsenm** [comment]
Changing the order fixes it for me

**Comment by nunoplopes** [comment]
Thank you; I had an old version of Z3 python files.
