### ISSUE TITLE
Support for float/double types?

### ISSUE THREAD

**Issue by LebedevRI** [nunoplopes/alive#41]
While investigating https://bugs.llvm.org/show_bug.cgi?id=36682,
i've come down to this: https://godbolt.org/g/bZyQ7r
But i'm unable to verify those optimizations via alive: https://rise4fun.com/Alive/aaAn
```
ERROR: Unknown conversion instruction (line: 1)
%1 = sitofp i32 %0 to double
     ^
```
Which makes sense, because not only the `sitofp` instruction is not supported, but there seems to be no base support for floating-point at all.

**Comment by santoshn** [comment]
You can use floating point types with the Alive-NJ prototype. Here is a link to the Alive-NJ github: https://github.com/rutgers-apl/alive-nj

**Comment by LebedevRI** [comment]
```
~/src/alive-nj$ ./run.py <....>/sitofp.opt     
----------                                                                      
  %2 = sitofp i32 %0 to double
  %3 = bitcast double %2 to i64
  %r = icmp slt i64 %3, 0
=>
  %r = icmp slt i32 %0, 0

Done: 1                                                                         
Optimization is correct
```
Yay, thanks!

Should i close this issue?
(Though, i did search before opening this issue, and somehow did not find the Alive-NJ)

**Comment by nunoplopes** [comment]
Right, Alive doesn't have any support for FP. Proper support is planed but won't happen in the next few months.
