### ISSUE TITLE
tests not done for i1?

### ISSUE THREAD

**Issue by lucvoo** [nunoplopes/alive#42]
I noticed that the following test succeed:
```
Name: sext-seteq1-in
%a = sext %X to i32
%r = icmp eq i32 %a, 1
  =>
%r = icmp eq %X, 1

```
but it should fail if %X is i1. This can be directly verified by giving the type explicitly:
```
Name: sext-seteq1-i1
%a = sext i1 %X to i32
%r = icmp eq i32 %a, 1
  =>
%r = icmp eq i1 %X, 1
```
which correctly fails.

Are the tests not done for i1? Am I missing something?

BTW, I noticed that the version running on https://rise4fun.com/Alive correctly
fails even when not given the explicit type. Is it running another version?

Thanks,
-- Luc

**Comment by nunoplopes** [comment]
rise4fun.com is running the newsema branch. The master branch is not being maintained at the moment.
I recommend you switch to newsema if possible.

**Comment by lucvoo** [comment]
OK. Thanks.

**Comment by regehr** [comment]
Nuno I wonder if it makes sense to just merge newsema into master in this case?

**Comment by nunoplopes** [comment]
I should do that, yes. The only blocker is that the codegen part got rotten in the newsema branch, so I didn't want to destroy it in master as well. I wanted to fix that bit before merging.
