### ISSUE TITLE
https://rise4fun.com/Alive fails with "Error:no output from Alive"

### ISSUE THREAD

**Issue by fhahn** [nunoplopes/alive#47]
It seems like https://rise4fun.com/Alive fails on some inputs that Alive can handle locally. e.g.

```
%a = sdiv %X, C
%r = sub undef, %a
  =>
%r = sdiv %X, -C
```  

fails online with `ERROR: no output from Alive`. Locally, alive reports `ERROR: Domain of definedness of Target is smaller than Source's for i4 %r`. 

Without the `undef`, online Alive produces usable output.

**Comment by nunoplopes** [comment]
This is now working, thanks for the report! Though rise4fun.com still has the buggy output cached.
You can perturb the input a bit to make it work, like in last line: "-C -> -C+0"

**Comment by fhahn** [comment]
awesome, thanks!
