### ISSUE TITLE
Instability of undef in input vars is not accounted for

### ISSUE THREAD

**Issue by ch3root** [nunoplopes/alive#48]
AIUI Alive can deal with `undef`s. In particular, `undef` should be among potential values for input variables. Right? Then there is a problem: according to the [LangRef](https://llvm.org/docs/LangRef.html#undefined-values) `undef`s are unstable and this seems not to be accounted for in Alive.

Simple example -- https://rise4fun.com/Alive/yjtD:
```llvm
%r = and i32 %Y, 0
=>
%r = xor i32 %Y, %Y
```
Both `and` and `xor` are taken from examples in LangRef, `and` here should always give `0` and `xor` here gives `undef`, so this transformation is not valid. But Alive says that it is.

More realistic example -- https://rise4fun.com/Alive/PpoX:
```llvm
%c = icmp eq i32 %X, %Y
%r = select i1 %c, i32 %X, 0
=>
%c = icmp eq i32 %X, %Y
%r = select i1 %c, i32 %Y, 0
```
When `%Y` is `undef`, the comparison gives `undef`, and `select` in the source can choose either `%X` or `0`. But we get `undef` in the target.

This is kinda simplified from https://bugs.llvm.org/show_bug.cgi?id=44512.

**Comment by nunoplopes** [comment]
The website still uses the old version of Alive, given that Alive2 doesn't match all features yet.
Alive2 reports both of your examples as buggy.
```
$ alive file.opt
----------------------------------------
  %r = and i32 %Y, 0
  ret i32 %r
=>
  %r = xor i32 %Y, %Y
  ret i32 %r

ERROR: Value mismatch for i32 %r

Example:
i32 %Y = undef
Source value: #x00000000 (0)
Target value: #x00000001 (1)
```

And the 2nd:
```
$ alive file.opt
----------------------------------------
  %c = icmp eq i32 %X, %Y
  %r = select i1 %c, i32 %X, 0
  ret i32 %r
=>
  %c = icmp eq i32 %X, %Y
  %r = select i1 %c, i32 %Y, 0
  ret i32 %r

ERROR: Value mismatch for i32 %r

Example:
i32 %X = #x08000000 (134217728)
i32 %Y = undef
i1 %c = undef
Source value: #x00000000 (0)    [based on undef value]
Target value: #x40000000 (1073741824)
```

There's no ETA yet on when we can upgrade the website to use Alive2.

**Comment by nunoplopes** [comment]
Alive2: https://github.com/AliveToolkit/alive2
No further development of Alive is planned.

**Comment by ch3root** [comment]
Cool, thanks, I'm now looking into building Alive2.

But this means that Alive is unsound, right? Shouldn't there be a warning to this effect, or something?

**Comment by nunoplopes** [comment]
That's correct. No verification tool is fully sound FWIW.
The goal is to migrate ASAP to Alive2 and don't waste much time with old stuff.
